4.1 unit-tests
js-tasks-ru/nodejs-20210907_serafina661 pull request #4
Opened 2021-10-08 00:01 UTC by Sera-Fina

2021-10-08 00:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-11 05:40 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-10-11 18:09 UTC, tadjik1 requested changes
@Sera-Fina раскомментируйте, пожалуйста, тесты для chat-app, пускай даже они упадут. я все равно зачту вам задачу с валидатором, а задачу с чатом вы сможете решить после нее

2021-10-12 09:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-12 09:04 UTC, tadjik1 approved these changes
@Sera-Fina спасибо!

2021-10-12 09:04 UTC, merged